export type { LLMProvider, MatchResult, Report, RockyConfig, Ticket } from './types'
export { DEFAULT_PROMPT_TEMPLATE, defaultConfig, resolveConfig } from './config'
export { diceSimilarity, match, normalize } from './match'
export { openaiProvider } from './providers'
export type { OpenAIProviderOptions } from './providers'
export { formatEvalReport, parsePairs, runEval } from './eval'
export type { EvalPair, EvalReport, EvalRunStats, LLMDelta, PairOutcome, TierCounts } from './eval'
