export type { LLMProvider, MatchResult, Report, RockyConfig, TaskAnalysis, Ticket } from './types'
export { DEFAULT_PROMPT_TEMPLATE, defaultConfig, resolveConfig } from './config'
export { diceSimilarity, match, normalize } from './match'
export { openaiProvider } from './providers'
export type { OpenAIProviderOptions } from './providers'
export { formatEvalReport, parsePairs, runEval } from './eval'
export type { EvalPair, EvalReport, EvalRunStats, LLMDelta, PairOutcome, TierCounts } from './eval'
export type { Source } from './sources/types'
export { sentrySource } from './sources/sentry'
export type { SentrySourceOptions } from './sources/sentry'
export { gmailSource, oauthRefreshAuth } from './sources/gmail'
export type { GmailSourceOptions, OAuthRefreshAuthOptions } from './sources/gmail'
export { reactionTrigger, slackSource } from './sources/slack'
export type { ReactionTriggerOptions, SlackSourceOptions } from './sources/slack'
export { webhookSource } from './sources/webhook'
export type { WebhookMapper, WebhookSource, WebhookSourceOptions } from './sources/webhook'
export { defineConfig, assertProjectConfig } from './project'
export type { RockyProjectConfig } from './project'
export { run } from './run'
export type { RunEvent, RunOptions, RunSummary } from './run'
export { approve, deny, formatStatus, watch } from './watch'
export type { WatchEvent, WatchOptions, WatchSummary } from './watch'
export { SEEN_CAP, TICKET_CAP, emptyState, loadState, pruneTickets, saveState } from './state'
export type { RockyState, TicketPhase, TicketProgress } from './state'
export { assertGatedSink } from './sinks/types'
export type { GatedSink, LabelChange, Sink, TicketResolution } from './sinks/types'
export { githubSink } from './sinks/github'
export type { GithubSinkOptions } from './sinks/github'
export { linearSink } from './sinks/linear'
export type { LinearSinkOptions } from './sinks/linear'
export type { Notifier, NotifyKind, NotifyMessage } from './notify/types'
export { approvalMessage, completedMessage, failedMessage, startedMessage, ticketRef } from './notify/format'
export { consoleNotifier } from './notify/console'
export type { ConsoleNotifierOptions } from './notify/console'
export { hermesNotifier } from './notify/hermes'
export type { HermesCliNotifierOptions, HermesNotifierOptions, HermesWebhookNotifierOptions } from './notify/hermes'
export { readBoard, serve } from './serve'
export type { BoardData, BoardTicket, ServeOptions } from './serve'
export { DASHBOARD_HTML } from './dashboard'
export { doctor, formatDoctorReport } from './doctor'
export type { CheckResult, DoctorOptions } from './doctor'
export { analyze, analysisSection, parseAnalysis, DEFAULT_ANALYSIS_TEMPLATE } from './analyze'
export type { AnalyzeOptions } from './analyze'
// Ticket-body helpers, public because CONTRIBUTING invites custom sinks and a
// hand-written one should format its tickets exactly like the shipped ones —
// including putting the analysis first and the original report below it.
export { annotationBody, firstLine, reportFacts, ticketBody } from './sinks/format'
export { investigate, findingBody, parseFindings, DEFAULT_INVESTIGATION_TEMPLATE } from './investigate'
export type { Evidence, Finding, InvestigateOptions } from './investigate'
export { signaturesOf } from './match'
